import Modal from "@/components/Modal";
import Sidebar from "@/components/Sidebar";
import SinglePost from "@/components/SinglePost";
import Trending from "@/components/Trending";
import { AppContext } from "@/contexts/AppContext";
import React, { useContext } from "react";

const PostPage = () => {
  const [appContext] = useContext(AppContext);
  return (
    <div>
      <title>Tweet Reply</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="" />

      <main className="relative max-w-[1400px] mx-auto">
        <Sidebar />
        <div className="flex gap-6">
          <SinglePost />
        </div>
        <Trending />
        {appContext?.isModalOpen && <Modal />}
      </main>
    </div>
  );
};

export default PostPage;
